testing code to reschedule on failure and allow user specified staging and harvesting file lists

diff --git a/vappio-scripts/sge/epilog b/vappio-scripts/sge/epilog
--- a/vappio-scripts/sge/epilog
+++ b/vappio-scripts/sge/epilog
@@ -63,7 +63,14 @@ if [ -n "$request_cwd" ]; then
     vappio_data_placement=1
     if [ -n "$vappio_data_placement" ]; then
 	vappio_scripts=$vappio_root
-	$vappio_scripts/sge/vappio_epilog.sh $hostname $request_cwd
+	$vappio_scripts/sge/vappio_epilog.sh $hostname $request_cwd 1>> $vappio_log 2>> $vappio_log
+	ret1=$?
+	vlog "vappio_epilog return code: $ret1"
+	if [ $ret1 -ne 0 ] 
+	    then
+	    echo echo "I~~~vappio harvesting failure. See $vappio_log";
+	    exit $ret1
+	fi 
     fi
 fi > /dev/null 2>&1
 
